version: '2'
services:
    db:
        image: ilios/mysql:v3.64.1
        environment:
            - MYSQL_USER=ilios
            - MYSQL_PASSWORD=ilios
            - MYSQL_DATABASE=ilios
            - MYSQL_RANDOM_ROOT_PASSWORD=false
            - MYSQL_ROOT_PASSWORD=1234root5678
        ports:
            - "17103:3306"
    web:
        image: ilios/php-apache:v3.64.1
        ports:
            - "8000:80"
        volumes:
            - ./logs:/var/www/ilios/var/logs:rw
